const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding Production DB...");

  // 1. Create Users & Profiles
  
  // Patient User
  const patientUser = await prisma.user.upsert({
    where: { phoneNumber: '9075012345' },
    update: {},
    create: {
      phoneNumber: '9075012345',
      role: 'PATIENT',
      isVerified: true,
      patient: {
        create: {
          fullName: 'Neha Kulkarni',
          gender: 'Female',
          dateOfBirth: new Date('1998-05-14'),
          bloodGroup: 'O+'
        }
      }
    },
    include: { patient: true }
  });

  // Doctor User
  const doctorUser = await prisma.user.upsert({
    where: { phoneNumber: '9876543210' },
    update: {},
    create: {
      phoneNumber: '9876543210',
      role: 'DOCTOR',
      isVerified: true,
      doctor: {
        create: {
          fullName: 'Dr. Amit Patil',
          specialization: 'Orthopedic Surgeon',
          experienceYears: 12,
          consultationFee: 500,
          languages: 'Marathi, Hindi, English',
          verificationStatus: true
        }
      }
    },
    include: { doctor: true }
  });

  // Hospital
  const hospital = await prisma.hospital.upsert({
    where: { registrationNumber: 'HOSP-12345' },
    update: {},
    create: {
      name: 'HealthSync Multi-Specialty Hospital',
      registrationNumber: 'HOSP-12345',
      city: 'Pune',
      emergencyAvailable: true,
      ambulanceAvailable: true,
      clinics: {
        create: [
          {
            name: 'Orthopedics Wing'
          }
        ]
      }
    },
    include: { clinics: true }
  });

  const clinic = hospital.clinics[0];

  // Link Doctor to Clinic
  const doctorClinic = await prisma.doctorClinic.findFirst({
    where: { doctorId: doctorUser.doctor.id, clinicId: clinic.id }
  });

  if (!doctorClinic) {
    await prisma.doctorClinic.create({
      data: {
        doctorId: doctorUser.doctor.id,
        clinicId: clinic.id,
        consultationFee: 500
      }
    });
  }

  // Generate availability
  // In a real scenario, this would be generated by the doctor UI
  // I will just create a generic mock availability if not exists
  console.log("Database successfully seeded.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
